// TODO: deprecate after getting API

import { BookDataI } from '../pages/book/types';

export const BookListDummy: BookDataI[] = [
  {
    id: 1,
    isStar: true,
    itemTitle: 'Грокаем алгоритмы. Иллюстрированное пособие для програ...',
    itemSubtitle: 'Адитья Бхаргава, 2019',
    bookId: 'noPhoto',
    img: 'cat',
  },
  {
    id: 2,
    isStar: true,
    itemTitle: 'Грокаем алгоритмы. Иллюстрированное пособие для програ...',
    itemSubtitle: 'Адитья Бхаргава, 2019',
    bookId: 'onePhoto',
    img: 'algo',
  },
  {
    id: 3,
    isStar: true,
    itemTitle: 'Грокаем алгоритмы. Иллюстрированное пособие для програ...',
    itemSubtitle: 'Адитья Бхаргава, 2019',
    bookId: 'morePhotos',
    img: ['algo', 'algo', 'algo', 'algo'],
  },
  {
    id: 4,
    isStar: true,
    itemTitle: 'Грокаем алгоритмы. Иллюстрированное пособие для програ...',
    itemSubtitle: 'Адитья Бхаргава, 2019',
    bookId: 'newBook',
    img: 'algo',
  },
  {
    id: 5,
    isStar: true,
    itemTitle: 'Грокаем алгоритмы. Иллюстрированное пособие для програ...',
    itemSubtitle: 'Адитья Бхаргава, 2019',
    bookId: 'newBook',
    img: 'algo',
  },
  {
    id: 6,
    isStar: true,
    itemTitle: 'Не грокаем',
    itemSubtitle: 'Адитья Бхаргава, 2019',
    bookId: 'bookId',
    img: 'algo',
  },
  {
    id: 7,
    isStar: true,
    itemTitle: 'Не грокаем',
    itemSubtitle: 'Адитья Бхаргава, 2019',
    bookId: 'bookId',
    img: 'algo',
  },
  {
    id: 8,
    isStar: true,
    itemTitle: 'Не грокаем',
    itemSubtitle: 'Адитья Бхаргава, 2019',
    bookId: 'bookId',
    img: 'algo',
  },
  {
    id: 9,
    isStar: true,
    itemTitle: 'Не грокаем',
    itemSubtitle: 'Адитья Бхаргава, 2019',
    bookId: 'bookId',
    img: 'algo',
  },
  {
    id: 10,
    isStar: true,
    itemTitle: 'Не грокаем',
    itemSubtitle: 'Адитья Бхаргава, 2019',
    bookId: 'bookId',
    img: 'algo',
  },
];
